### ISSUE TITLE
MORPH_OPEN is not declared

### ISSUE THREAD

**Issue by ythknakamura** [theothergrantdavidson/opencv-ts#16]
Thank you for the wonderful project.
I found that `MORPH_OPEN`, a member of the `MorphTypes`, is not declared in both `ImageFiltering.d.ts` and `opencv.d.ts`.

**Comment by Piemontez** [comment]
Thanks, I will check it,

**Comment by theothergrantdavidson** [comment]
Added in this PR and published with version 1.2.27 https://github.com/theothergrantdavidson/opencv-ts/pull/24
