### ISSUE TITLE
cv.imread() overload in types definition

### ISSUE THREAD

**Issue by hillin** [theothergrantdavidson/opencv-ts#3]
`cv.imread()` should be able to accept either an id string or a reference to a canvas or image element. The element reference overload seems absent in the types definition.

**Comment by theothergrantdavidson** [comment]
Thanks for pointing it out, still actively working on this so if you come past anything feel free to open more issues. Updated [here](https://github.com/theothergrantdavidson/opencv-ts/commit/a447e086551c885644a29ee6db18209eb48c9961#diff-168dc98bb6dffd08b42476951c5682d5781bad7cc27ee74992d644b43a00cddaR204)

**Comment by hillin** [comment]
Thanks for the quick response, good job!
