### ISSUE TITLE
cannot use fillPoly 

### ISSUE THREAD

**Issue by zuixiaosanlang** [theothergrantdavidson/opencv-ts#8]
![image](https://user-images.githubusercontent.com/20105627/138205680-fd3e0519-5ca1-4780-a3c4-0f1fbf3369f5.png)

pts: Point ??
what is wrong? in c++，there are many points ;

**Comment by theothergrantdavidson** [comment]
Fixed in this merge 
https://github.com/theothergrantdavidson/opencv-ts/commit/e178017545f7b7ab3ea78225b592c265bd2160e7
